sudo:required
services:
  - docker
   
before_install:
  - docker build -t rooqleen/docker-react -f Dockerfile.dev .

script:
  - docker run rooqleen/docker-react npm run test -- --coverage

#nothing




